[
  {
    "id": 32818188,
    "title": "Verify that the Scan endpoint is returning a valid response with all the correct parameters.",
    "section_id": 1865887,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708549332,
    "updated_by": 370,
    "updated_on": 1708967334,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 1,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the API endpoint is \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\"\r\nAnd the request payload contains valid scanFacility code, scanArea code, scanDevice code, patronAccountIds, eventIds, scanMediaType, and scanType.\r\n    ",
    "custom_test_purpose": null,
    "custom_steps": "When I make a POST request\r\n{\r\n\t\"validateId\": {\r\n\t\t\"scanFacility\": {\r\n\t\t\t\"code\": \"STAD\"\r\n\t\t},\r\n\t\t\"scanArea\": {\r\n\t\t\t\"code\": \"QA\"\r\n\t\t},\r\n\t\t\"scanDevice\": {\r\n\t\t\t\"code\": \"QA\"\r\n\t\t},\r\n\t\t\"patronAccountIds\": [\r\n\t\t\t38609\r\n\t\t],\r\n\t\t\"eventIds\": [\r\n\t\t\t2983\r\n\t\t],\r\n\t\t\"scanMediaType\": \"FR\",\r\n\t\t\"scanType\": \"BM\"\r\n\t}\r\n}",
    "custom_expected": "Then the response status code should be 200\r\nAnd the response body should not contain any error code\r\nAnd the scanResult should reflect a valid Entry\r\n \"scanResults\": [\r\n                {\r\n                    \"active\": true,\r\n                    \"code\": \"PVVE\",\r\n                    \"description\": \"Valid Entry\",\r\n                    \"displayOrder\": 500,\r\n                    \"publicDescription\": \"Valid Entry\",\r\n                    \"refIndex\": 0,\r\n                    \"refKey\": \"PVVE\",\r\n                    \"type\": \"VALID_ENTRY\"\r\n                }",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32839074,
    "title": "Verify access denial for reentry on the same day with \"Enteries exceeded for Event\" error code",
    "section_id": 1865887,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708967956,
    "updated_by": 370,
    "updated_on": 1708968164,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 2,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the API endpoint is \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\"\r\nAnd the request payload contains valid scanFacility code, scanArea code, scanDevice code, patronAccountIds, eventIds, scanMediaType, and scanType.\r\n    ",
    "custom_test_purpose": null,
    "custom_steps": "When I make a POST request again for the same \"Event\" (When the Patron tries to reenter the same event)\r\n{\r\n\t\"validateId\": {\r\n\t\t\"scanFacility\": {\r\n\t\t\t\"code\": \"STAD\"\r\n\t\t},\r\n\t\t\"scanArea\": {\r\n\t\t\t\"code\": \"QA\"\r\n\t\t},\r\n\t\t\"scanDevice\": {\r\n\t\t\t\"code\": \"QA\"\r\n\t\t},\r\n\t\t\"patronAccountIds\": [\r\n\t\t\t38609\r\n\t\t],\r\n\t\t\"eventIds\": [\r\n\t\t\t2983\r\n\t\t],\r\n\t\t\"scanMediaType\": \"FR\",\r\n\t\t\"scanType\": \"BM\"\r\n\t}\r\n}",
    "custom_expected": "Then the response status code should be 200\r\nThen the access should be denied\r\nAnd the scanResult should reflect a invalid Entry\r\n   \"scanResults\": [\r\n                {\r\n                    \"active\": true,\r\n                    \"code\": \"PVEE\",\r\n                    \"description\": \"Entries Exceeded For Event\",\r\n                    \"displayOrder\": 500,\r\n                    \"publicDescription\": \"Entry Limit Exceeded\",\r\n                    \"refIndex\": 0,\r\n                    \"refKey\": \"PVEE\",\r\n                    \"type\": \"INVALID_ENTRY\"\r\n                }",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32839075,
    "title": "Verify that Access Control for Patron Entry Limit is allowable per \"Valid Scans Per Day\" in accessControl.",
    "section_id": 1865887,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708979253,
    "updated_by": 370,
    "updated_on": 1708980205,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 3,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the API endpoint is \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\"\r\nAnd the patron with permission to scan per day is 2\r\n    ",
    "custom_test_purpose": null,
    "custom_steps": "When the patron makes an API call to the access control system\r\nThen the patron should be allowed up to two entries\r\nAnd if the patron tries to enter more than two times",
    "custom_expected": "Then an error code is displayed in the response.\r\n\"\"\"\r\n\"scanResults\": [\r\n{\r\n\"active\": true,\r\n\"code\": \"PVEE\",\r\n\"description\": \"Entries Exceeded For Event\",\r\n\"displayOrder\": 500,\r\n\"publicDescription\": \"Entry Limit Exceeded\",\r\n\"refIndex\": 0,\r\n\"refKey\": \"PVEE\",\r\n\"type\": \"INVALID_ENTRY\"\r\n}\r\n\"\"\"\r\nAnd the patron should not be allowed to enter again",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32818189,
    "title": "Verify that the Scan end point with all the missing parameters is NOT returning a Valid response.",
    "section_id": 1865887,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708549446,
    "updated_by": 370,
    "updated_on": 1708967481,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 4,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the API endpoint is \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\"\r\nAnd the request payload missing value for scanFacility code, scanArea code, scanDevice code, patronAccountIds, eventIds, scanMediaType, and scanType.\r\n",
    "custom_test_purpose": null,
    "custom_steps": "When I make a POST request\r\n{\r\n\t\"validateId\": {\r\n\t\t\"scanFacility\": {\r\n\t\t\t\"code\": \"\"\r\n\t\t},\r\n\t\t\"scanArea\": {\r\n\t\t\t\"code\": \"\"\r\n\t\t},\r\n\t\t\"scanDevice\": {\r\n\t\t\t\"code\": \"\"\r\n\t\t},\r\n\t\t\"patronAccountIds\": [\r\n\t\t\r\n\t\t],\r\n\t\t\"eventIds\": [\r\n\t\t\t\r\n\t\t],\r\n\t\t\"scanMediaType\": \"\",\r\n\t\t\"scanType\": \"\"\r\n\t}\r\n}",
    "custom_expected": "Then the response status code should be 400\r\nAnd the response body should contain error Message.\r\n        \"code\": \"pv.common.20012\",\r\n        \"httpMethod\": \"POST\",\r\n        \"requestUrl\": \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\",\r\n        \"message\": \"The following fields are required: ['validateId.patronAccountIds','validateId.scanArea.code','validateId.scanDevice.code','validateId.scanFacility.code'].\"\r\n    }\r\n}",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32839265,
    "title": "Verify that multiple Patron IDs are allowed in the payload body, and that the response contains valid data for multiple patrons.",
    "section_id": 1865887,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708982122,
    "updated_by": 370,
    "updated_on": 1709051805,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 5,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the API endpoint is \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\"\r\nAnd the request payload contains multiple Patron IDs",
    "custom_test_purpose": null,
    "custom_steps": "When I make a POST request\r\n{\r\n    \"validateId\": {\r\n        \"scanFacility\": {\r\n            \"code\": \"STAD\"\r\n        },\r\n        \"scanArea\": {\r\n            \"code\": \"QA\"\r\n        },\r\n        \"scanDevice\": {\r\n            \"code\": \"QA\"\r\n        },\r\n        \"patronAccountIds\": [\r\n            38609,38175\r\n        ],\r\n        \"eventIds\": [\r\n            2983\r\n        ],\r\n        \"scanMediaType\": \"FR\",\r\n        \"scanType\": \"BM\"\r\n    }\r\n}",
    "custom_expected": "Then the response status code should be 200\r\nAnd the response body should include responses for multiple patrons as specified in the payload\r\n\r\nhttps://splunk.tixx.tickets.com/en-US/app/PV/search?earliest=-5m%40m&latest=now&q=search%20sourcetype%3Dpv-*%20env_name%3D%22QASTK1%20US%22%2038609&display.page.search.mode=smart&dispatch.sample_ratio=1&sid=1709051625.1353194_29D947ED-9811-41C7-AD4F-D97EE60D78F0\r\n2024-02-27 08:31:47,768 [operatorId=, userLogin=, agencyId=, agencyCode=, x-datadog-trace-id=1916074221730635454, threadId=http-nio-8080-exec-49] INFO  [com.tickets.api2.filter.ApiInboundLoggingFilter] Inbound Message\r\n... 20 lines omitted ...\r\n        },\r\n        \"patronAccountIds\": [\r\n            38609,38175\r\n        ],",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32818190,
    "title": "Verify the response with Invalid scanFacility code",
    "section_id": 1865887,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708549558,
    "updated_by": 370,
    "updated_on": 1708625893,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 8,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the API endpoint is \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\"\r\nAnd the request payload contains an invalid scanFacility code",
    "custom_test_purpose": null,
    "custom_steps": "When I make a POST request with invalid scanFacility\r\n\r\n{\r\n\t\"validateId\": {\r\n\t\t\"scanFacility\": {\r\n\t\t\t\"code\": \"STAD13523\"\r\n\t\t},\r\n\t\t\"scanArea\": {\r\n\t\t\t\"code\": \"QA\"\r\n\t\t},\r\n\t\t\"scanDevice\": {\r\n\t\t\t\"code\": \"QA\"\r\n\t\t},\r\n\t\t\"patronAccountIds\": [\r\n\t\t\t38175\r\n\t\t],\r\n\t\t\"eventIds\": [\r\n\t\t\t5809\r\n\t\t],\r\n\t\t\"scanMediaType\": \"FR\",\r\n\t\t\"scanType\": \"BM\"\r\n\t}\r\n}",
    "custom_expected": "Current States: response code is 200\r\nAnd the response body returns with proper response.\r\n\r\n(Check with Steve or Mitch regarding the implementation for mismatch scanFacility)\r\n",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32818191,
    "title": "Verify that the response is not valid due to an invalid scanArea code.",
    "section_id": 1865887,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708549628,
    "updated_by": 370,
    "updated_on": 1709055750,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 11,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the API endpoint is \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\"\r\nAnd the request payload contains an invalid scanArea code",
    "custom_test_purpose": null,
    "custom_steps": "When I make a POST request with an invalid scanArea\r\n\r\n{\r\n\t\"validateId\": {\r\n\t\t\"scanFacility\": {\r\n\t\t\t\"code\": \"STAD\"\r\n\t\t},\r\n\t\t\"scanArea\": {\r\n\t\t\t\"code\": \"QA1\"\r\n\t\t},\r\n\t\t\"scanDevice\": {\r\n\t\t\t\"code\": \"QA\"\r\n\t\t},\r\n\t\t\"patronAccountIds\": [\r\n\t\t\t38175\r\n\t\t],\r\n\t\t\"eventIds\": [\r\n\t\t\t5809\r\n\t\t],\r\n\t\t\"scanMediaType\": \"FR\",\r\n\t\t\"scanType\": \"BM\"\r\n\t}\r\n}",
    "custom_expected": "Then the response status code should be 404\r\nAnd the response body should contain the error \"message\": {\r\n    \"error\": {\r\n        \"code\": \"pv.common.40006\",\r\n        \"httpMethod\": \"POST\",\r\n        \"requestUrl\": \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\",\r\n        \"message\": \"A business error has occurred in the core application which has not been mapped to a specific error message/code for this API. An error was logged with reference number 'API1708980341878'. The details of the error are as follows: 'Scan Area QA1 is not associated with Scan Facility STAD.'\"\r\n    }\r\n}",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32818192,
    "title": "Verify the response with Invalid scanDevice code",
    "section_id": 1865887,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708549692,
    "updated_by": 370,
    "updated_on": 1709055713,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 12,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the API endpoint is \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\"\r\nAnd the request payload contains an invalid scanDevice code",
    "custom_test_purpose": null,
    "custom_steps": "When I make a POST request with an invalid scanDevice code\r\n\r\n{\r\n\t\"validateId\": {\r\n\t\t\"scanFacility\": {\r\n\t\t\t\"code\": \"STAD\"\r\n\t\t},\r\n\t\t\"scanArea\": {\r\n\t\t\t\"code\": \"QA\"\r\n\t\t},\r\n\t\t\"scanDevice\": {\r\n\t\t\t\"code\": \"QA1\"\r\n\t\t},\r\n\t\t\"patronAccountIds\": [\r\n\t\t\t38609\r\n\t\t],\r\n\t\t\"eventIds\": [\r\n\t\t\t2983\r\n\t\t],\r\n\t\t\"scanMediaType\": \"FR\",\r\n\t\t\"scanType\": \"BM\"\r\n\t}\r\n}",
    "custom_expected": "Then the response status code should be 404\r\nAnd the response body should contain the error {\r\n    \"error\": {\r\n        \"code\": \"pv.common.40006\",\r\n        \"httpMethod\": \"POST\",\r\n        \"requestUrl\": \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\",\r\n        \"message\": \"A business error has occurred in the core application which has not been mapped to a specific error message/code for this API. An error was logged with reference number 'API1708980803945'. The details of the error are as follows: 'Scan Device QA1 is not associated with Scan Area QA.'\"\r\n    }\r\n}",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32820040,
    "title": "Verify the response with Invalid patronAccountIds",
    "section_id": 1865887,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708611850,
    "updated_by": 370,
    "updated_on": 1708981954,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 13,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the API endpoint is \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\"\r\nAnd the request payload contains invalid patronAccountIds\r\n",
    "custom_test_purpose": null,
    "custom_steps": "When I make a POST request with invalid patronAccountIds (386091)\r\n\r\n{\r\n\t\"validateId\": {\r\n\t\t\"scanFacility\": {\r\n\t\t\t\"code\": \"STAD\"\r\n\t\t},\r\n\t\t\"scanArea\": {\r\n\t\t\t\"code\": \"QA\"\r\n\t\t},\r\n\t\t\"scanDevice\": {\r\n\t\t\t\"code\": \"QA\"\r\n\t\t},\r\n\t\t\"patronAccountIds\": [\r\n\t\t\t386091\r\n\t\t],\r\n\t\t\"eventIds\": [\r\n\t\t\t2983\r\n\t\t],\r\n\t\t\"scanMediaType\": \"FR\",\r\n\t\t\"scanType\": \"BM\"\r\n\t}\r\n}",
    "custom_expected": "Then the response status code should be 404\r\nAnd the response body should contain the error \"message\": \r\n    \"error\": {\r\n        \"code\": \"pv.accesscontrol.50006\",\r\n        \"httpMethod\": \"POST\",\r\n        \"requestUrl\": \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\",\r\n        \"message\": \"No eligible tickets found for entry. These patron accounts not found or archived, patronAccountIds=[386091].\"\r\n    }\r\n}",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32839267,
    "title": "Verify that the response with multiple Patron IDs returns the valid response for a valid Patron AccountId only",
    "section_id": 1865887,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708983113,
    "updated_by": 370,
    "updated_on": 1708983373,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 14,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the API endpoint is \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\"\r\nAnd the request payload contains one valid and one invalid patronAccountIds\r\n",
    "custom_test_purpose": null,
    "custom_steps": "When I make a POST request with invalid patronAccountIds (386091)(38175)\r\n\r\n{\r\n    \"validateId\": {\r\n        \"scanFacility\": {\r\n            \"code\": \"STAD\"\r\n        },\r\n        \"scanArea\": {\r\n            \"code\": \"QA\"\r\n        },\r\n        \"scanDevice\": {\r\n            \"code\": \"QA\"\r\n        },\r\n        \"patronAccountIds\": [\r\n            386091,38175\r\n        ],\r\n        \r\n        \"eventIds\": [\r\n            2983\r\n        ],\r\n        \"scanMediaType\": \"FR\",\r\n        \"scanType\": \"BM\"\r\n    }\r\n}",
    "custom_expected": "Then the response status code should be 200\r\nAnd the response body should contain the response for the valid Patron ID and null response for the invalid Patron ID.",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32820041,
    "title": "Verify that the response with Invalid eventIds returns 404 response",
    "section_id": 1865887,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708611927,
    "updated_by": 370,
    "updated_on": 1708983668,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 15,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the API endpoint is \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\"\r\nAnd the request payload contains invalid eventIds",
    "custom_test_purpose": null,
    "custom_steps": "When I make a POST request with the invalid eventIds (29831)\r\n\r\n{\r\n    \"validateId\": {\r\n        \"scanFacility\": {\r\n            \"code\": \"STAD\"\r\n        },\r\n        \"scanArea\": {\r\n            \"code\": \"QA\"\r\n        },\r\n        \"scanDevice\": {\r\n            \"code\": \"QA\"\r\n        },\r\n        \"patronAccountIds\": [\r\n            38609\r\n        ],\r\n        \r\n        \"eventIds\": [\r\n            29831\r\n        ],\r\n        \"scanMediaType\": \"FR\",\r\n        \"scanType\": \"BM\"\r\n    }\r\n}",
    "custom_expected": "Then the response status code should be 404\r\nAnd the response body should contain the error \"message\": {\r\n    \"error\": {\r\n        \"code\": \"pv.common.50002\",\r\n        \"httpMethod\": \"POST\",\r\n        \"requestUrl\": \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\",\r\n        \"message\": \"An Event with ID '29831' is not found.\"\r\n    }\r\n}",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32820042,
    "title": "Verify that the response with Invalid scanMediaType returns a bad response with 400",
    "section_id": 1865887,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708612031,
    "updated_by": 370,
    "updated_on": 1708983804,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 17,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the API endpoint is \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\"\r\nAnd the request payload contains invalid scanMediaType",
    "custom_test_purpose": null,
    "custom_steps": "When I make a POST request\r\n{\r\n\t\"validateId\": {\r\n\t\t\"scanFacility\": {\r\n\t\t\t\"code\": \"STAD\"\r\n\t\t},\r\n\t\t\"scanArea\": {\r\n\t\t\t\"code\": \"QA\"\r\n\t\t},\r\n\t\t\"scanDevice\": {\r\n\t\t\t\"code\": \"QA\"\r\n\t\t},\r\n\t\t\"patronAccountIds\": [\r\n\t\t\t38175\r\n\t\t],\r\n\t\t\"eventIds\": [\r\n\t\t\t5809\r\n\t\t],\r\n\t\t\"scanMediaType\": \"FR1\",\r\n\t\t\"scanType\": \"BM\"\r\n\t}\r\n}",
    "custom_expected": "Then the response status code should be 400\r\nAnd the response body should contain the error \"message\": {\r\n    \"error\": {\r\n        \"code\": \"pv.common.20008\",\r\n        \"httpMethod\": \"POST\",\r\n        \"requestUrl\": \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\",\r\n        \"message\": \"The parameter 'validateId.scanMediaType' with the value 'FR1' is not valid.\"\r\n    }\r\n}",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32820043,
    "title": "Verify that the input with Invalid scanType returns a Bad response of 400",
    "section_id": 1865887,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708612151,
    "updated_by": 370,
    "updated_on": 1708983982,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 18,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the API endpoint is \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\"\r\nAnd the request payload contains invalid scanType (BM1)",
    "custom_test_purpose": null,
    "custom_steps": "When I make a POST request\r\n\r\n{\r\n\t\"validateId\": {\r\n\t\t\"scanFacility\": {\r\n\t\t\t\"code\": \"STAD\"\r\n\t\t},\r\n\t\t\"scanArea\": {\r\n\t\t\t\"code\": \"QA\"\r\n\t\t},\r\n\t\t\"scanDevice\": {\r\n\t\t\t\"code\": \"QA\"\r\n\t\t},\r\n\t\t\"patronAccountIds\": [\r\n\t\t\t38175\r\n\t\t],\r\n\t\t\"eventIds\": [\r\n\t\t\t5809\r\n\t\t],\r\n\t\t\"scanMediaType\": \"FR\",\r\n\t\t\"scanType\": \"BM1\"\r\n\t}\r\n}",
    "custom_expected": "Then the response status code should be 400\r\nAnd the response body should contain the error \"message\": \"The parameter 'validateId.scanType' with the value 'BM1' is not valid.\"\r\n{\r\n    \"error\": {\r\n        \"code\": \"pv.common.20008\",\r\n        \"httpMethod\": \"POST\",\r\n        \"requestUrl\": \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\",\r\n        \"message\": \"The parameter 'validateId.scanType' with the value 'BM1' is not valid.\"\r\n    }\r\n}",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32820051,
    "title": "Verify that there is an appropriate response for the Missing scanFacility code",
    "section_id": 1865887,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708614348,
    "updated_by": 370,
    "updated_on": 1709058750,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 19,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the API endpoint is \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\"\r\nAnd the request payload does not contain a scanFacility code",
    "custom_test_purpose": null,
    "custom_steps": "When I make a POST request\r\n\r\n{\r\n\t\"validateId\": {\r\n\t\t\"scanFacility\": {\r\n\t\t\t\"code\": \"\"\r\n\t\t},\r\n\t\t\"scanArea\": {\r\n\t\t\t\"code\": \"QA\"\r\n\t\t},\r\n\t\t\"scanDevice\": {\r\n\t\t\t\"code\": \"QA\"\r\n\t\t},\r\n\t\t\"patronAccountIds\": [\r\n\t\t\t38175\r\n\t\t],\r\n\t\t\"eventIds\": [\r\n\t\t\t5809\r\n\t\t],\r\n\t\t\"scanMediaType\": \"FR\",\r\n\t\t\"scanType\": \"BM1\"\r\n\t}\r\n}",
    "custom_expected": "Then the response status code should be 400\r\nAnd the response body should contain the response with\r\n{\r\n    \"error\": {\r\n        \"code\": \"pv.common.20012\",\r\n        \"httpMethod\": \"POST\",\r\n        \"requestUrl\": \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\",\r\n        \"message\": \"The following fields are required: ['validateId.scanFacility.code'].\"\r\n    }\r\n}\r\nAnd when the scanFacility code contains a single character or a number, the response should be returned successfully. ",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32820052,
    "title": "Verify the response with the missing scanArea code and the extra parameter for scanArea",
    "section_id": 1865887,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708614553,
    "updated_by": 370,
    "updated_on": 1709046437,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 20,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the API endpoint is \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\"\r\nAnd the request payload does not contain a scanArea code\r\nAnd the request payload contain an extra parameter for the scanArea code\r\n",
    "custom_test_purpose": null,
    "custom_steps": "When I make a POST request\r\n\r\n{  \"validateId\": {  \r\n\"scanFacility\": {  \r\n\"code\": \"STAD\"  \r\n},  \r\n\"scanArea\": {  \r\n\"code\": \"QA\",  \r\n\"extraParameter\": \"value\"  \r\n},  \r\n\"scanDevice\": {  \r\n\"code\": \"QA\"  \r\n},  \r\n\"patronAccountIds\": [  \r\n38609  \r\n],  \r\n\"eventIds\": [  \r\n2983  \r\n],  ",
    "custom_expected": "Then the response status code should be 400\r\nAnd the response body should contain the error message:\r\n{\r\n    \"error\": {\r\n        \"code\": \"pv.common.20012\",\r\n        \"httpMethod\": \"POST\",\r\n        \"requestUrl\": \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\",\r\n        \"message\": \"The following fields are required: ['validateId.scanArea.code'].\"\r\n    }\r\n}\r\nAND if an extra Parameter is add to the scanArea.\r\nThen the response status code should be 415\r\n{\r\n    \"error\": {\r\n        \"code\": \"pv.proxy.20003\",\r\n        \"httpMethod\": \"POST\",\r\n        \"requestUrl\": \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\",\r\n        \"message\": \"The request payload/content is in an invalid format.\"\r\n    }\r\n}\r\n",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32820053,
    "title": "Verify that the response with Missing scanDevice returns the appropriate error message",
    "section_id": 1865887,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708614651,
    "updated_by": 370,
    "updated_on": 1709046617,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 21,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the API endpoint is \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\"\r\nAnd the request payload does not contain a scanDevice code",
    "custom_test_purpose": null,
    "custom_steps": "When I make a POST request\r\n\r\n{\r\n\t\"validateId\": {\r\n\t\t\"scanFacility\": {\r\n\t\t\t\"code\": \"STAD\"\r\n\t\t},\r\n\t\t\"scanArea\": {\r\n\t\t\t\"code\": \"QA\"\r\n\t\t},\r\n\t\t\"scanDevice\": {\r\n\t\t\t\"code\": \"\"\r\n\t\t},\r\n\t\t\"patronAccountIds\": [\r\n\t\t\t38175\r\n\t\t],\r\n\t\t\"eventIds\": [\r\n\t\t\t5809\r\n\t\t],\r\n\t\t\"scanMediaType\": \"FR\",\r\n\t\t\"scanType\": \"BM\"\r\n\t}\r\n}",
    "custom_expected": "Then the response status code should be 400\r\nAnd the response body should contain the error message\r\n{\r\n    \"error\": {\r\n        \"code\": \"pv.common.20012\",\r\n        \"httpMethod\": \"POST\",\r\n        \"requestUrl\": \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\",\r\n        \"message\": \"The following fields are required: ['validateId.scanDevice.code'].\"\r\n    }\r\n}",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32820054,
    "title": "Verify that the response with Missing patronAccountIds returns the appropriate error message",
    "section_id": 1865887,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708614944,
    "updated_by": 370,
    "updated_on": 1709046579,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 22,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the API endpoint is \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\"\r\nAnd the request payload does not contain patronAccountIds",
    "custom_test_purpose": null,
    "custom_steps": "When I make a POST request\r\n\r\n{\r\n\t\"validateId\": {\r\n\t\t\"scanFacility\": {\r\n\t\t\t\"code\": \"STAD\"\r\n\t\t},\r\n\t\t\"scanArea\": {\r\n\t\t\t\"code\": \"QA\"\r\n\t\t},\r\n\t\t\"scanDevice\": {\r\n\t\t\t\"code\": \"QA\"\r\n\t\t},\r\n\t\t\"patronAccountIds\": [\r\n\t\t\r\n\t\t],\r\n\t\t\"eventIds\": [\r\n\t\t\t5809\r\n\t\t],\r\n\t\t\"scanMediaType\": \"FR\",\r\n\t\t\"scanType\": \"BM\"\r\n\t}\r\n}",
    "custom_expected": "Then the response status code should be 400\r\nAnd the response body should contain the error message: \r\n{\r\n    \"error\": {\r\n        \"code\": \"pv.common.20012\",\r\n        \"httpMethod\": \"POST\",\r\n        \"requestUrl\": \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\",\r\n        \"message\": \"The following fields are required: ['validateId.patronAccountIds'].\"\r\n    }\r\n}",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32820056,
    "title": "Verify that request with Missing Payload Body returns an appropriate response",
    "section_id": 1865887,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708621662,
    "updated_by": 370,
    "updated_on": 1709046880,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 23,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the API endpoint is \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\"\r\nAnd the request does not contain the Payload Body",
    "custom_test_purpose": null,
    "custom_steps": "When I make a POST request",
    "custom_expected": "Then the response status code should be 404 with the error Message.\r\n",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32820059,
    "title": "Verify that the missing scanMediaType return the response to the defaults value",
    "section_id": 1865887,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708626044,
    "updated_by": 370,
    "updated_on": 1709047256,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 24,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the API endpoint is \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\"\r\nAnd the request payload does not contain scanMediaType",
    "custom_test_purpose": null,
    "custom_steps": "When I make a POST request\r\n\r\n{\r\n\t\"validateId\": {\r\n\t\t\"scanFacility\": {\r\n\t\t\t\"code\": \"STAD\"\r\n\t\t},\r\n\t\t\"scanArea\": {\r\n\t\t\t\"code\": \"QA\"\r\n\t\t},\r\n\t\t\"scanDevice\": {\r\n\t\t\t\"code\": \"QA\"\r\n\t\t},\r\n\t\t\"patronAccountIds\": [\r\n\t\t\t38175\r\n\t\t],\r\n\t\t\"eventIds\": [\r\n\t\t\t5809\r\n\t\t],\r\n\t\t\"scanMediaType\": \"\",\r\n\t\t\"scanType\": \"BM\"\r\n\t}\r\n}",
    "custom_expected": "Then the response status code should be 200 with default value.\r\n },\r\n                    \"scanMediaType\": \"FACIAL_RECOGNITION\",\r\n                    \"scanArea\": {\r\n                        \"refIndex\": 0,\r\n                        \"refKey\": \"1865\",\r\n                        \"refSet\": \"scanAreas\"\r\n                    },\r\nAnd the Patron has a valid entry\r\n\"scanResults\": [\r\n                {\r\n                    \"active\": true,\r\n                    \"code\": \"PVVE\",\r\n                    \"description\": \"Valid Entry\",\r\n                    \"displayOrder\": 500,\r\n                    \"publicDescription\": \"Valid Entry\",\r\n                    \"refIndex\": 0,\r\n                    \"refKey\": \"PVVE\",\r\n                    \"type\": \"VALID_ENTRY\"\r\n                }\r\n            ],\r\n            \r\n",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32820057,
    "title": "Verify that the endpoint can be successfully called without providing the optional parameter \"event id\".",
    "section_id": 1865887,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708623229,
    "updated_by": 370,
    "updated_on": 1709048011,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 26,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the API endpoint is \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\"\r\nAnd the request payload does not contain the eventIds",
    "custom_test_purpose": null,
    "custom_steps": "When I make a POST request with out the eventId\r\n\r\n{\r\n\t\"validateId\": {\r\n\t\t\"scanFacility\": {\r\n\t\t\t\"code\": \"STAD\"\r\n\t\t},\r\n\t\t\"scanArea\": {\r\n\t\t\t\"code\": \"QA\"\r\n\t\t},\r\n\t\t\"scanDevice\": {\r\n\t\t\t\"code\": \"QA\"\r\n\t\t},\r\n\t\t\"patronAccountIds\": [\r\n\t\t\t38175\r\n\t\t],\r\n\t\t\"eventIds\": [\r\n\t\t\t\r\n\t\t],\r\n\t\t\"scanMediaType\": \"FR\",\r\n\t\t\"scanType\": \"BM\"\r\n\t}\r\n}",
    "custom_expected": "Then the response with Status code: 200\r\nAnd the response body returns the event with a default value.\r\n  },\r\n                \"event\": {\r\n                    \"refIndex\": 0,\r\n                    \"refKey\": \"2979\",\r\n                    \"refSet\": \"events\"\r\n                },",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32822952,
    "title": "Validate API response when providing unsupported parameters like totp and scanOperator (Entry scan)",
    "section_id": 1865887,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708629038,
    "updated_by": 370,
    "updated_on": 1709049035,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 27,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the API endpoint is \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\"\r\n    And the request payload contains unsupported parameters \"totp\" and \"scanOperator\"",
    "custom_test_purpose": null,
    "custom_steps": "When I make a POST request\r\n{\r\n    \"validateId\": {\r\n        \"scanFacility\": {\r\n            \"code\": \"STAD\"\r\n        },\r\n        \"scanArea\": {\r\n            \"code\": \"QA\"\r\n        },\r\n        \"scanDevice\": {\r\n            \"code\": \"QA\"\r\n        },\r\n        \"patronAccountIds\": [\r\n            38609\r\n        ],\r\n        \r\n        \"eventIds\": [\r\n            \r\n        ],\r\n        \"scanMediaType\": \"FR\",\r\n        \"scanType\": \"BM\"\r\n    },\r\n    \"exitScan\": \"false\",\r\n    \"totp\": \"6546546564\",\r\n    \"totpTimestamp\": \"464565465\"\r\n}",
    "custom_expected": "Then the response status code should be 400\r\nAnd the response body should contain an error code for unsupported parameters\r\n{\r\n    \"error\": {\r\n        \"code\": \"pv.common.20034\",\r\n        \"requestUrl\": \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\",\r\n        \"message\": \"An error occurred while validating the structure and expected data types. The payload is not valid near line '22' and column '5'. The reference is 'API1709048231808'.\"\r\n    }\r\n}",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32845496,
    "title": "Validate API response when providing unsupported parameters like totp and scanOperator (Exit scan)",
    "section_id": 1865887,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1709049092,
    "updated_by": 370,
    "updated_on": 1709049270,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 28,
    "custom_is_automated": false,
    "custom_pv_category": 2,
    "custom_refs": null,
    "custom_preconds": "Given the API endpoint is \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\"\r\nAnd the request payload contains unsupported parameters \"totp\" and \"scanOperator\" (Exit scan)",
    "custom_test_purpose": null,
    "custom_steps": "When I make a post call\r\n{\r\n    \"validateId\": {\r\n        \"scanFacility\": {\r\n            \"code\": \"STAD\"\r\n        },\r\n        \"scanArea\": {\r\n            \"code\": \"QA\"\r\n        },\r\n        \"scanDevice\": {\r\n            \"code\": \"QA\"\r\n        },\r\n        \"patronAccountIds\": [\r\n            38609\r\n        ],\r\n        \r\n        \"eventIds\": [\r\n            \r\n        ],\r\n        \"scanMediaType\": \"FR\",\r\n        \"scanType\": \"BM\"\r\n    },\r\n    \"exitScan\": \"true\",\r\n    \"totp\": \"6546546564\",\r\n    \"totpTimestamp\": \"464565465\"\r\n}",
    "custom_expected": "Then the response status code should be 400\r\nAnd the response body should contain an error code for unsupported parameters\r\n{\r\n\"error\": {\r\n\"code\": \"pv.common.20034\",\r\n\"requestUrl\": \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\",\r\n\"message\": \"An error occurred while validating the structure and expected data types. The payload is not valid near line '22' and column '5'. The reference is 'API1709048231808'.\"\r\n}\r\n}\r\n",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32825135,
    "title": "Ticket is successfully scanned and shows up as printed",
    "section_id": 1866514,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708631092,
    "updated_by": 370,
    "updated_on": 1709154690,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 1,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given User initiates a ticket sales via UI https://qastk1u.provenueapp.com:18443/springapp/ticketsales/mapsales/mapSales.jsp?event.id=5628\r\nAnd User selects a delivery method other than print now\r\nAnd User selects cash as payment method\r\nAnd User checks out a successful transaction",
    "custom_test_purpose": null,
    "custom_steps": "Then a ticket_print_detail record is created without any name-value pairs\r\nAnd User verifies that the ticket status does not reflect scanned\r\nThen User initiates an API call to validate the ticket scan at curl --location 'https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan' \\\r\n--header 'Content-Type: application/json' \\\r\n--header 'Authorization: Bearer RBUtG1NghsccOPXenzoGqEEXCGmK' \\\r\n--data '{\r\n\"validateId\": {\r\n\"scanFacility\": {\r\n\"code\": \"STAD\"\r\n},\r\n\"scanArea\": {\r\n\"code\": \"QA\"\r\n},\r\n\"scanDevice\": {\r\n\"code\": \"QA\"\r\n},\r\n\"patronAccountIds\": [\r\n44243\r\n],\r\n\r\n    \"eventIds\": [\r\n       5628\r\n    ],\r\n    \"scanMediaType\": \"FR\",\r\n }\r\n}'",
    "custom_expected": "Then the response should return with the success status code 200\r\nAnd the ticket status should change to printed and scanned\r\n\r\n",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32825136,
    "title": "Ticket is scanned successfully but does not show up as printed",
    "section_id": 1866514,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708631168,
    "updated_by": 370,
    "updated_on": 1708631216,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 2,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the ticket is valid and has not been scanned before",
    "custom_test_purpose": null,
    "custom_steps": "When the ticket is scanned successfully",
    "custom_expected": "Then the scan should be recorded in the TICKET_PRINT_SCAN record\r\nAnd the ticket should not show up as printed",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32825137,
    "title": "Ticket is scanned successfully with correct SMT and shows up as printed",
    "section_id": 1866514,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708631238,
    "updated_by": 370,
    "updated_on": 1709229870,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 3,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the ticket is valid and has not been scanned before\r\nGiven User initiates a ticket sales via UI https://qastk1u.provenueapp.com:18443/springapp/ticketsales/mapsales/mapSales.jsp?event.id=5628\r\nAnd User selects a delivery method print now\r\nGiven the ticket is valid and has not been scanned before\r\n\r\n",
    "custom_test_purpose": null,
    "custom_steps": "When the ticket is scanned successfully with an correct SMT\r\nAnd user initiate a scan api call to https://ph31mldvapppvn10.back.tickets.com:18443/api/v2/accessControl/validate/id/scan\r\n{\r\n    \"validateId\": {\r\n        \"eventIds\": [4282],\r\n        \"patronAccountIds\": [2941],\r\n        \"scanArea\": {\r\n            \"code\": \"DEFAULT\"\r\n        },\r\n        \"scanDevice\": {\r\n            \"code\": \"DEFAULT\"\r\n        },\r\n        \"scanFacility\": {\r\n            \"code\": \"DEFAULT\"\r\n        },\r\n        \"scanMediaType\": \"FR\",\r\n        \"scanType\": \"BIOMETRIC\"\r\n    }\r\n}",
    "custom_expected": "Then the scan should not be recorded in the TICKET_PRINT_SCAN record\r\nAnd the ticket shoul show up as printed\r\n\r\n![](index.php?/attachments/get/13995420)\r\n",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32868803,
    "title": "Ticket is scanned with incorrect SMT and does not show up as printed",
    "section_id": 1866514,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1709229878,
    "updated_by": 370,
    "updated_on": 1709230173,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 4,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the ticket is valid and has not been scanned before\r\nGiven User initiates a ticket sales via UI https://qastk1u.provenueapp.com:18443/springapp/ticketsales/mapsales/mapSales.jsp?event.id=5628\r\nAnd User selects a delivery method print now\r\nGiven the ticket is valid and has not been scanned before\r\n\r\n",
    "custom_test_purpose": null,
    "custom_steps": "When the ticket is scanned with an incorrect SMT\r\nAnd user initiate a scan api call to https://ph31mldvapppvn10.back.tickets.com:18443/api/v2/accessControl/validate/id/scan\r\n{\r\n    \"validateId\": {\r\n        \"eventIds\": [4282],\r\n        \"patronAccountIds\": [2941],\r\n        \"scanArea\": {\r\n            \"code\": \"DEFAULT\"\r\n        },\r\n        \"scanDevice\": {\r\n            \"code\": \"DEFAULT\"\r\n        },\r\n        \"scanFacility\": {\r\n            \"code\": \"DEFAULT\"\r\n        },\r\n        \"scanMediaType\": \"FR123\",\r\n        \"scanType\": \"BIOMETRIC\"\r\n    }\r\n}",
    "custom_expected": "Then the scan should not be recorded in the TICKET_PRINT_SCAN record\r\nAnd the ticket should not show up as printed\r\nAnd the response body should return an appropriate status code: 400\r\n{\r\n    \"error\": {\r\n        \"code\": \"pv.common.20008\",\r\n        \"httpMethod\": \"POST\",\r\n        \"requestUrl\": \"https://ph31mldvapppvn10.back.tickets.com:18443/api/v2/accessControl/validate/id/scan\",\r\n        \"message\": \"The parameter 'validateId.scanMediaType' with the value 'FR123' is not valid.\"\r\n    }\r\n}\r\n\r\n",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32825139,
    "title": "Ticket is scanned with error PVIL and shows up as printed",
    "section_id": 1866514,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708631328,
    "updated_by": 370,
    "updated_on": 1709231427,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 9,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the ticket is valid and has not been scanned before\r\nGiven User initiates a ticket sales via UI https://qastk1u.provenueapp.com:18443/springapp/eventadmin/eventAdminDetails?event.id=5627&cid=d3629908-844c-49b6-b21f-25710cda57a7\r\nAnd User selects a delivery method OTHER than print now\r\nAnd User selects cash as payment method\r\nAnd User checks out a successful transaction\r\nAnd the tickets status reflect to \"printed: 0\"\r\nAnd the limit of scan entry per day/event set to 1\r\n",
    "custom_test_purpose": null,
    "custom_steps": "When initiates an API call to validate the ticket scan at curl --location https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan' \\\r\n{\r\n    \"validateId\": {\r\n        \"scanFacility\": {\r\n            \"code\": \"STAD\"\r\n        },\r\n        \"scanArea\": {\r\n            \"code\": \"QA\"\r\n        },\r\n        \"scanDevice\": {\r\n            \"code\": \"QA\"\r\n        },\r\n        \"patronAccountIds\": [\r\n            44243\r\n        ],\r\n    \r\n        \"eventIds\": [\r\n           5627\r\n        ],\r\n        \"scanMediaType\": \"FR\",\r\n        \"scanType\": \"BM\"\r\n    }\r\n}\r\nAnd the User initiate the same call more than once.",
    "custom_expected": "Then the scan should not be recorded in the TICKET_PRINT_SCAN record\r\nAnd the ticket should not show up as printed\r\nAnd the response body should return the appropriate status code: 200\r\n   {\r\n                    \"active\": true,\r\n                    \"code\": \"PVEE\",\r\n                    \"description\": \"Entries Exceeded For Event\",\r\n                    \"displayOrder\": 500,\r\n                    \"publicDescription\": \"Entry Limit Exceeded\",\r\n                    \"refIndex\": 0,\r\n                    \"refKey\": \"PVEE\",\r\n                    \"type\": \"INVALID_ENTRY\"\r\n                },\r\n",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32825751,
    "title": "Patron with ticket to the event where the AC is disabled",
    "section_id": 1866566,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708631954,
    "updated_by": 370,
    "updated_on": 1709064760,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 1,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given I'm on the event admin page with event ID 2983\r\nAnd the patron has a ticket to the event\r\nAnd I click on Access control\r\n\r\n",
    "custom_test_purpose": null,
    "custom_steps": "When I uncheck the box for access control\r\nAnd the patron tries to access the event with API call https://test.pvapi.provenue.comv2/accessControl/validate/id/scan",
    "custom_expected": "Then the access control denies entry with status code 400\r\nAnd the response body should return an appropriate error message:\r\n{\r\n    \"error\": {\r\n        \"code\": \"pv.accesscontrol.20004\",\r\n        \"httpMethod\": \"POST\",\r\n        \"requestUrl\": \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\",\r\n        \"message\": \"Event with ID '2983' is not enabled for access control today.\"\r\n    }\r\n}",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32826815,
    "title": "Patron with tickets to event with AC not active yet",
    "section_id": 1866566,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708635156,
    "updated_by": 370,
    "updated_on": 1709066242,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 3,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the event has AC disabled for 30 min from the current time\r\nAnd the patron has a ticket to the event\r\n\r\n",
    "custom_test_purpose": null,
    "custom_steps": "When the patron tries to access the event with API call https://test.pvapi.provenue.comv2/accessControl/validate/id/scan",
    "custom_expected": "Then the access control should deny entry and return status code 400\r\nAnd the response body should return with an appropriate message:\r\n{\r\n    \"error\": {\r\n        \"code\": \"pv.accesscontrol.20004\",\r\n        \"httpMethod\": \"POST\",\r\n        \"requestUrl\": \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\",\r\n        \"message\": \"Event with ID '2983' is not enabled for access control today.\"\r\n    }\r\n}\r\n",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32826814,
    "title": "Patron with tickets enabled for today not allowed for another few hours",
    "section_id": 1866566,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708635111,
    "updated_by": 370,
    "updated_on": 1709067485,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 5,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given I'm on the event admin page with event ID 2983\r\nAnd the patron has tickets enabled for today but not allowed for another few hour\r\nAnd I click on Access control",
    "custom_test_purpose": null,
    "custom_steps": "When I click into the access control section\r\nAnd adjust the time to few hours from the Event. \r\nWhen the patron tries to access the event with API call https://test.pvapi.provenue.comv2/accessControl/validate/id/scan",
    "custom_expected": "Then the access control denies entry with status code 400\r\nAnd the response body should return an appropriate error message:\r\n{\r\n\"error\": {\r\n\"code\": \"pv.accesscontrol.20004\",\r\n\"httpMethod\": \"POST\",\r\n\"requestUrl\": \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\",\r\n\"message\": \"Event with ID '2983' is not enabled for access control today.\"\r\n}\r\n}\r\n",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32826816,
    "title": "Patron with no ticket to events on that day",
    "section_id": 1866566,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708637822,
    "updated_by": 370,
    "updated_on": 1709067454,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 6,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the patron has no tickets for any event on the current day\r\nAnd access the event with API call https://test.pvapi.provenue.comv2/accessControl/validate/id/scan",
    "custom_test_purpose": null,
    "custom_steps": "When I make a post call\r\n{\r\n    \"validateId\": {\r\n        \"scanFacility\": {\r\n            \"code\": \"STAD\"\r\n        },\r\n        \"scanArea\": {\r\n            \"code\": \"QA\"\r\n        },\r\n        \"scanDevice\": {\r\n            \"code\": \"QA\"\r\n        },\r\n        \"patronAccountIds\": [\r\n            44243\r\n        ],\r\n        \r\n        \"eventIds\": [\r\n            6876\r\n        ],\r\n        \"scanMediaType\": \"FR\",\r\n        \"scanType\": \"BM\"\r\n    }\r\n}",
    "custom_expected": "Then the access control should deny entry and return status code 404\r\nAnd the message body should return an appropriate response with error message\r\n{\r\n    \"error\": {\r\n        \"code\": \"pv.accesscontrol.50005\",\r\n        \"httpMethod\": \"POST\",\r\n        \"requestUrl\": \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\",\r\n        \"message\": \"No eligible tickets found for entry, patronAccountIds=[44243], eventIds=[6876], allowGoAheadEntryOnCurrentlyListedOnOfferTickets=true.\"\r\n    }\r\n}\r\nAnd the log should also reflect the same error\r\nhttps://splunk.tixx.tickets.com/en-US/app/PV/search?earliest=-5m%40m&latest=now&q=search%20sourcetype%3Dpv-*%20env_name%3D%22QASTK1%20US%22%2050005&display.page.search.mode=smart&dispatch.sample_ratio=1&sid=1709067328.1356760_29D947ED-9811-41C7-AD4F-D97EE60D78F0\r\n",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32825753,
    "title": "Patron with 1 ticket to only 1 event",
    "section_id": 1866566,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708631980,
    "updated_by": 370,
    "updated_on": 1709068035,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 7,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the patron now has exactly 1 ticket to 1 event\r\nAnd the access Control is enable for the patron with that given event\r\nAnd Patron logs proper Account ID and Event Id into the post call",
    "custom_test_purpose": null,
    "custom_steps": "When the patron tries to access the event with API call https://test.pvapi.provenue.comv2/accessControl/validate/id/scan\r\n",
    "custom_expected": "Then the response return with the success status code 200 OK\r\nAnd the access control should allow entry\r\nAnd is able to view the ticket detail for the event entered.",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32826820,
    "title": "Patron with multiple tickets to only 1 event on different day(not today)",
    "section_id": 1866566,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708637873,
    "updated_by": 370,
    "updated_on": 1709069785,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 8,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the patron has multiple tickets to 1 event on a different day (not today)\r\nGiven I'm on the event admin page with event ID 6876\r\nAnd the patron has tickets enabled",
    "custom_test_purpose": null,
    "custom_steps": "When I click into the access control section\r\nAnd adjust the time to different day\r\nWhen the patron tries to access the event with API call https://test.pvapi.provenue.comv2/accessControl/validate/id/scan\r\n",
    "custom_expected": "Then the access control denies entry with status code 400\r\nAnd the response body should return an appropriate error message:\r\n{\r\n{\r\n    \"error\": {\r\n        \"code\": \"pv.accesscontrol.20004\",\r\n        \"httpMethod\": \"POST\",\r\n        \"requestUrl\": \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\",\r\n        \"message\": \"Event with ID '6876' is not enabled for access control today.\"\r\n    }\r\n}",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32826819,
    "title": "Patron with multiple tickets to more than one event today",
    "section_id": 1866566,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708637866,
    "updated_by": 370,
    "updated_on": 1709130845,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 9,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the patron has multiple tickets to more than one event for today\r\nGiven I'm on the event admin page with event ID 6876\r\nAnd the patron has tickets enabled",
    "custom_test_purpose": null,
    "custom_steps": "When I click into the access control section\r\nAnd adjust the time to current\r\nWhen the patron tries to access the event with API call https://test.pvapi.provenue.comv2/accessControl/validate/id/scan\r\n\r\n\r\n",
    "custom_expected": "Then the response return with the success status code 200 OK\r\nAnd the access control should allow entry\r\nAnd is able to view the ticket detail for the event entered.",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32826818,
    "title": "Patron with events to multiple agencies only 1 agency is mapped to the calling operator",
    "section_id": 1866566,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708637860,
    "updated_by": 370,
    "updated_on": 1708638124,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 10,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the patron has tickets to events from multiple agencies\r\nAnd only 1 agency is mapped to the calling operator",
    "custom_test_purpose": null,
    "custom_steps": "When the patron tries to access the event with API call https://test.pvapi.provenue.comv2/accessControl/validate/id/scan\r\n",
    "custom_expected": "Then the access control should deny entry",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32826821,
    "title": "Patron with ticket to package with events across multiple days including today",
    "section_id": 1866566,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708638137,
    "updated_by": 370,
    "updated_on": 1709143878,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 11,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the patron has a ticket to a package with events across multiple days including today",
    "custom_test_purpose": null,
    "custom_steps": "When the patron tries to access the event with API call with multiple events from the Package. https://test.pvapi.provenue.comv2/accessControl/validate/id/scan\r\n{\r\n    \"validateId\": {\r\n        \"scanFacility\": {\r\n            \"code\": \"STAD\"\r\n        },\r\n        \"scanArea\": {\r\n            \"code\": \"QA\"\r\n        },\r\n        \"scanDevice\": {\r\n            \"code\": \"QA\"\r\n        },\r\n        \"patronAccountIds\": [\r\n            44243\r\n        ],\r\n        \r\n        \"eventIds\": [\r\n           5627, 2979,5809\r\n        ],\r\n",
    "custom_expected": "Then the response should return with the success status code 200 OK\r\n\r\nAnd the access control should allow entry for the scheduled event on the same day\r\n\r\n\"scanResults\": [\r\n\r\n{\r\n\r\n\"active\": true,\r\n\r\n\"code\": \"PVVE\",\r\n\r\n\"description\": \"Valid Entry\",\r\n\r\n\"displayOrder\": 500,\r\n\r\n\"publicDescription\": \"Valid Entry\",\r\n\r\n\"refIndex\": 0,\r\n\r\n\"refKey\": \"PVVE\",\r\n\r\n\"type\": \"VALID_ENTRY\"\r\n\r\n}\r\n\r\n\r\nAnd throw an exception error for the event that is not scheduled on the day\r\n\r\n{\r\n\r\n\"active\": true,\r\n\r\n\"code\": \"PVID\",\r\n\r\n\"description\": \"Incorrect Date\",\r\n\r\n\"displayOrder\": 500,\r\n\r\n\"publicDescription\": \"Not Valid on this Date\",\r\n\r\n\"refIndex\": 1,\r\n\r\n\"refKey\": \"PVID\",\r\n\r\n\"type\": \"INVALID_ENTRY\"\r\n\r\n}",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32826822,
    "title": "Patron with tickets for 2 events today where AC is enabled for one event right now but another event in another hour",
    "section_id": 1866566,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708638143,
    "updated_by": 370,
    "updated_on": 1709145637,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 12,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given the patron has tickets for 2 events today\r\nAnd AC is enabled for one event right now but another event in another hour",
    "custom_test_purpose": null,
    "custom_steps": "When the patron tries to access the event with API call with both events https://test.pvapi.provenue.comv2/accessControl/validate/id/scan\r\n{\r\n    \"validateId\": {\r\n        \"scanFacility\": {\r\n            \"code\": \"STAD\"\r\n        },\r\n        \"scanArea\": {\r\n            \"code\": \"QA\"\r\n        },\r\n        \"scanDevice\": {\r\n            \"code\": \"QA\"\r\n        },\r\n        \"patronAccountIds\": [\r\n            44243\r\n        ],\r\n        \r\n        \"eventIds\": [\r\n           5626,5628\r\n        ],\r\n        \"scanMediaType\": \"FR\",\r\n        \"scanType\": \"BM\"\r\n    }\r\n}",
    "custom_expected": "Then the response should return with the success status code 400\r\n\r\nAnd the access control should deny entry for the Event that is schedule for another hour.\r\n{\r\n    \"error\": {\r\n        \"code\": \"pv.accesscontrol.20004\",\r\n        \"httpMethod\": \"POST\",\r\n        \"requestUrl\": \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\",\r\n        \"message\": \"Event with ID '5626' is not enabled for access control today.\"\r\n    }\r\n}\r\nAnd Allow the entry for event that is schedule right now in access control\r\n \"scanResults\": [\r\n                {\r\n                    \"active\": true,\r\n                    \"code\": \"PVVE\",\r\n                    \"description\": \"Valid Entry\",\r\n                    \"displayOrder\": 500,\r\n                    \"publicDescription\": \"Valid Entry\",\r\n                    \"refIndex\": 0,\r\n                    \"refKey\": \"PVVE\",\r\n                    \"type\": \"VALID_ENTRY\"\r\n                }\r\n\r\n",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32834953,
    "title": "Scan ticket that has not been previously printed",
    "section_id": 1867087,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708724334,
    "updated_by": 370,
    "updated_on": 1709154676,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 1,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given User initiates a ticket sales via UI https://qastk1u.provenueapp.com:18443/springapp/ticketsales/mapsales/mapSales.jsp?event.id=5628\r\nAnd User selects a delivery method other than print now\r\nAnd User selects cash as payment method\r\nAnd User checks out a successful transaction",
    "custom_test_purpose": null,
    "custom_steps": "Then a ticket_print_detail record is created without any name-value pairs\r\nAnd User verifies that the ticket status does not reflect printed or scanned\r\nThen User initiates an API call to validate the ticket scan at curl --location 'https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan' \\\r\n--header 'Content-Type: application/json' \\\r\n--header 'Authorization: Bearer RBUtG1NghsccOPXenzoGqEEXCGmK' \\\r\n--data '{\r\n    \"validateId\": {\r\n        \"scanFacility\": {\r\n            \"code\": \"STAD\"\r\n        },\r\n        \"scanArea\": {\r\n            \"code\": \"QA\"\r\n        },\r\n        \"scanDevice\": {\r\n            \"code\": \"QA\"\r\n        },\r\n        \"patronAccountIds\": [\r\n            44243\r\n        ],\r\n        \r\n        \"eventIds\": [\r\n           5628\r\n        ],\r\n        \"scanMediaType\": \"FR\",\r\n        \"scanType\": \"BM\"\r\n    }\r\n}'",
    "custom_expected": "Then the response should return with the success status code 200\r\nAnd the ticket status should change to printed and scanned\r\n",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32855559,
    "title": "Scan ticket that has been printed and then scanned",
    "section_id": 1867087,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1709150432,
    "updated_by": 370,
    "updated_on": 1709218764,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 3,
    "custom_is_automated": false,
    "custom_pv_category": 1,
    "custom_refs": null,
    "custom_preconds": "Given User initiates a ticket sales via UI https://qastk1u.provenueapp.com:18443/springapp/ticketsales/mapsales/mapSales.jsp?event.id=5628\r\nAnd User selects a delivery method print now\r\nAnd User selects cash as payment method\r\nAnd User checks out a successful transaction",
    "custom_test_purpose": null,
    "custom_steps": "And User verifies that the ticket status only reflect printed and not scanned\r\nWhen User initiates an API call to validate the ticket scan at curl --location 'https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan' \\\r\n--header 'Content-Type: application/json' \\\r\n--header 'Authorization: Bearer RBUtG1NghsccOPXenzoGqEEXCGmK' \\\r\n--data '{\r\n    \"validateId\": {\r\n        \"scanFacility\": {\r\n            \"code\": \"STAD\"\r\n        },\r\n        \"scanArea\": {\r\n            \"code\": \"QA\"\r\n        },\r\n        \"scanDevice\": {\r\n            \"code\": \"QA\"\r\n        },\r\n        \"patronAccountIds\": [\r\n            44243\r\n        ],\r\n        \r\n        \"eventIds\": [\r\n           5628\r\n        ],\r\n        \"scanMediaType\": \"FR\",\r\n        \"scanType\": \"BM\"\r\n    }\r\n}'",
    "custom_expected": "Then the response should return with the success status code 200\r\nAnd the ticket status should also change to scanned\r\n",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32839068,
    "title": "Verify Failed scan on unprinted ticket",
    "section_id": 1867087,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708959753,
    "updated_by": 370,
    "updated_on": 1709218966,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 4,
    "custom_is_automated": false,
    "custom_pv_category": 2,
    "custom_refs": null,
    "custom_preconds": "Given User initiates a ticket sales via UI https://qastk1u.provenueapp.com:18443/springapp/ticketsales/mapsales/mapSales.jsp?event.id=5628\r\nAnd User selects a delivery method OTHER then print now\r\nAnd User selects cash as payment method\r\nAnd User checks out a successful transaction\r\n\r\n",
    "custom_test_purpose": null,
    "custom_steps": "When a user attempts to scan an unprinted ticket with a fail call\r\nAnd User initiates an API call to validate the ticket scan at curl --location 'https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan' \\\r\n--header 'Content-Type: application/json' \\\r\n--header 'Authorization: Bearer RBUtG1NghsccOPXenzoGqEEXCGmK' \\\r\n--data '{\r\n\"validateId\": {\r\n\"scanFacility\": {\r\n\"code\": \"STAD\"\r\n},\r\n\"scanArea\": {\r\n\"code\": \"QA\"\r\n},\r\n\"scanDevice\": {\r\n\"code\": \"QA\"\r\n},\r\n\"patronAccountIds\": [\r\n44243\r\n],\r\n\r\n    \"eventIds\": [\r\n       5628\r\n    ],\r\n    \"scanMediaType\": \"FR1\",\r\n    \"scanType\": \"BM\"\r\n}\r\n}'",
    "custom_expected": "Then a ticket_print_detail record is created in the log even though the scan failed\r\nResponse-Code: 400\r\nContent-Type: application/json\r\nHeaders: {Content-Type=[application/json], Date=[Thu, 29 Feb 2024 14:53:31 GMT], PV-Request-ID=[200]}\r\nAPI Operation: ACCESS_CONTROL_VALIDATE_ID_SCAN\r\nPayload: \r\n{\"error\":{\"code\":\"pv.common.20008\",\"httpMethod\":\"POST\",\"requestUrl\":\"https://qastk1u.pvapi.provenueapp.com:443:18443/v2/accessControl/validate/id/scan\",\"message\":\"The parameter 'validateId.scanMediaType' with the value 'FR1' is not valid.\"}}\r\n\r\nAnd the ticket status remains \"unprinted",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32868788,
    "title": "Verify ticket prints after scan failure",
    "section_id": 1867087,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1709219013,
    "updated_by": 370,
    "updated_on": 1709219415,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 6,
    "custom_is_automated": false,
    "custom_pv_category": 2,
    "custom_refs": null,
    "custom_preconds": "Given User initiates a ticket sales via UI https://qastk1u.provenueapp.com:18443/springapp/ticketsales/mapsales/mapSales.jsp?event.id=5628\r\nAnd User selects a delivery method print now\r\nAnd User selects cash as payment method\r\nAnd User checks out a successful transaction\r\n\r\n",
    "custom_test_purpose": null,
    "custom_steps": "When a user attempts to scan an printed ticket with a fail call\r\nAnd User initiates an API call to validate the ticket scan at curl --location 'https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan' \\\r\n--header 'Content-Type: application/json' \\\r\n--header 'Authorization: Bearer RBUtG1NghsccOPXenzoGqEEXCGmK' \\\r\n--data '{\r\n\"validateId\": {\r\n\"scanFacility\": {\r\n\"code\": \"STAD\"\r\n},\r\n\"scanArea\": {\r\n\"code\": \"QA\"\r\n},\r\n\"scanDevice\": {\r\n\"code\": \"QA1\"\r\n},\r\n\"patronAccountIds\": [\r\n44243\r\n],\r\n\r\n    \"eventIds\": [\r\n       5628\r\n    ],\r\n    \"scanMediaType\": \"FR\",\r\n    \"scanType\": \"BM\"\r\n}\r\n}'",
    "custom_expected": "Then a ticket_print_detail record is created in the log even though the scan failed\r\nAPI Operation: ACCESS_CONTROL_VALIDATE_ID_SCAN\r\nPayload: \r\n{\"error\":{\"code\":\"pv.common.40006\",\"httpMethod\":\"POST\",\"requestUrl\":\"https://qastk1u.pvapi.provenueapp.com:443:18443/v2/accessControl/validate/id/scan\",\"message\":\"A business error has occurred in the core application which has not been mapped to a specific error message/code for this API. An error was logged with reference number 'API1709219289493'. The details of the error are as follows: 'Scan Area QA1 is not associated with Scan Facility STAD.'\"}}\r\n\r\nAnd the ticket status remains \"printed\" and not scanned",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32839070,
    "title": "Print, reset, and scan and verfiy",
    "section_id": 1867087,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708962759,
    "updated_by": 370,
    "updated_on": 1709220930,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 7,
    "custom_is_automated": false,
    "custom_pv_category": 2,
    "custom_refs": null,
    "custom_preconds": "Given User initiates a ticket sales via UI https://qastk1u.provenueapp.com:18443/springapp/ticketsales/mapsales/mapSales.jsp?event.id=5628\r\nAnd User selects a delivery method print now\r\nAnd User selects cash as payment method\r\nAnd User checks out a successful transaction\r\nAnd the tickets status reflect to \"printed\"",
    "custom_test_purpose": null,
    "custom_steps": "When the user selects the Reset print header dropdown from the select action.\r\nWhen user clicks on the Apply action button\r\nAnd the ticket status is updated to \"Printed: 0\"\r\n User initiates an API call to validate the ticket scan at curl --location 'https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan' \\\r\n--header 'Content-Type: application/json' \\\r\n--header 'Authorization: Bearer RBUtG1NghsccOPXenzoGqEEXCGmK' \\\r\n--data '{\r\n\"validateId\": {\r\n\"scanFacility\": {\r\n\"code\": \"STAD\"\r\n},\r\n\"scanArea\": {\r\n\"code\": \"QA\"\r\n},\r\n\"scanDevice\": {\r\n\"code\": \"QA\"\r\n},\r\n\"patronAccountIds\": [\r\n44243\r\n],\r\n\r\n    \"eventIds\": [\r\n       6874\r\n    ],\r\n    \"scanMediaType\": \"FR\",\r\n    \"scanType\": \"BM\"\r\n}\r\n}'\r\n",
    "custom_expected": "Then the response should return with the success status code 200\r\nAnd the ticket status should change to printed and scanned\r\nAnd status for each action is reflected in the log as expected.\r\nhttps://splunk.tixx.tickets.com/en-US/app/PV/search?earliest=-5m%40m&latest=now&q=search%20sourcetype%3Dpv-*%20env_name%3D%22QASTK1%20US%22%2016916021&display.page.search.mode=smart&dispatch.sample_ratio=1&sid=1709220856.1390325_29D947ED-9811-41C7-AD4F-D97EE60D78F0\r\n",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32839071,
    "title": "Multiple tickets scanned and printed",
    "section_id": 1867087,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1708962954,
    "updated_by": 370,
    "updated_on": 1709220588,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 9,
    "custom_is_automated": false,
    "custom_pv_category": 2,
    "custom_refs": null,
    "custom_preconds": "Given User initiates a ticket sales via UI https://qastk1u.provenueapp.com:18443/springapp/ticketsales/mapsales/mapSales.jsp?event.id=5628\r\nWhen user select multiple ticket to purchase \r\nAnd User selects a delivery method other than print now\r\nWhen User selects cash as payment method\r\nAnd User checks out a successful transaction\r\nAnd the tickets status reflect to \"printed: 0\"",
    "custom_test_purpose": null,
    "custom_steps": "When user initiates an API call to validate the ticket scan: curl --location 'https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan' \\\r\n--header 'Content-Type: application/json' \\\r\n--header 'Authorization: Bearer RBUtG1NghsccOPXenzoGqEEXCGmK' \\\r\n--data '{\r\n\"validateId\": {\r\n\"scanFacility\": {\r\n\"code\": \"STAD\"\r\n},\r\n\"scanArea\": {\r\n\"code\": \"QA\"\r\n},\r\n\"scanDevice\": {\r\n\"code\": \"QA\"\r\n},\r\n\"patronAccountIds\": [\r\n44243\r\n],\r\n\r\n\"eventIds\": [\r\n   5627\r\n],\r\n\"scanMediaType\": \"FR\",\r\n\"scanType\": \"BM\"\r\n}\r\n},",
    "custom_expected": "Then each scan and print operation is successful and the response return with status code: 200\r\nAnd the ticket status for each ticket remains \"printed\"\r\nAnd the response body has valid entry for all the scanned tickets\r\n\"scanResults\": [\r\n                {\r\n                    \"active\": true,\r\n                    \"code\": \"PVVE\",\r\n                    \"description\": \"Valid Entry\",\r\n                    \"displayOrder\": 500,\r\n                    \"publicDescription\": \"Valid Entry\",\r\n                    \"refIndex\": 0,\r\n                    \"refKey\": \"PVVE\",\r\n                    \"type\": \"VALID_ENTRY\"\r\n                }\r\n            ],",
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32856701,
    "title": "Patron Account is locked and ticket was not printed previously",
    "section_id": 1869293,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1709155873,
    "updated_by": 370,
    "updated_on": 1709156043,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 1,
    "custom_is_automated": false,
    "custom_pv_category": 2,
    "custom_refs": null,
    "custom_preconds": "Given the patron account is locked\r\nAnd the ticket was not printed previously",
    "custom_test_purpose": "When the user submits the patron account lock details https://qastk1u.provenueapp.com:18443/springapp/utility/patronlock/submitPatronAccountLockDetails?patronAccount.id=44243\r\nAnd user make a post call to https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan",
    "custom_steps": "Then the ticket should be filtered out\r\nAnd there should be no printing or scanning of the ticket\r\nThe response should return with appropriate status code 404\r\n{\r\n    \"error\": {\r\n        \"code\": \"pv.accesscontrol.50005\",\r\n        \"httpMethod\": \"POST\",\r\n        \"requestUrl\": \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\",\r\n        \"message\": \"No eligible tickets found for entry, patronAccountIds=[44243], eventIds=[6874], allowGoAheadEntryOnCurrentlyListedOnOfferTickets=true.\"\r\n    }\r\n}",
    "custom_expected": null,
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  },
  {
    "id": 32856704,
    "title": "Patron Account is locked and ticket was printed previously",
    "section_id": 1869293,
    "template_id": 1,
    "type_id": 4,
    "priority_id": 6,
    "milestone_id": null,
    "refs": null,
    "created_by": 370,
    "created_on": 1709156135,
    "updated_by": 370,
    "updated_on": 1709156210,
    "estimate": null,
    "estimate_forecast": null,
    "suite_id": 663158,
    "display_order": 3,
    "custom_is_automated": false,
    "custom_pv_category": 2,
    "custom_refs": null,
    "custom_preconds": "Given the patron account is locked\r\nAnd the ticket were printed previously",
    "custom_test_purpose": "When the user submits the patron account lock details https://qastk1u.provenueapp.com:18443/springapp/utility/patronlock/submitPatronAccountLockDetails?patronAccount.id=44243\r\nAnd user make a post call to https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan",
    "custom_steps": "Then the ticket should be filtered out\r\nAnd there should be no printing or scanning of the ticket\r\nThe response should return with appropriate status code 404\r\n{\r\n    \"error\": {\r\n        \"code\": \"pv.accesscontrol.50005\",\r\n        \"httpMethod\": \"POST\",\r\n        \"requestUrl\": \"https://test.pvapi.provenue.com/v2/accessControl/validate/id/scan\",\r\n        \"message\": \"No eligible tickets found for entry, patronAccountIds=[44243], eventIds=[6874], allowGoAheadEntryOnCurrentlyListedOnOfferTickets=true.\"\r\n    }\r\n}",
    "custom_expected": null,
    "custom_steps_separated": null,
    "custom_comment": null,
    "custom_jiras": null
  }
]